name: Pull Request Checks
on:
  pull_request:
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Format
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: fmt
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Imports
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Shadow
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: shadow
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Static Check
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Vet
        uses: grandcolline/golang-github-actions@v1.1.0
        with:
          run: vet
          token: ${{ secrets.GITHUB_TOKEN }}
  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: shogo82148/actions-goveralls@v1

